name: flutter_country_state
description: A customizable Flutter package that displays all countries with it respective state.
version: 0.2.9
homepage: https://github.com/mimi-tech/flutter_country_state

environment:
  sdk: ">=2.17.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

